# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --production --ignore-scripts

# Copy the rest of the application
COPY . .

# Expose port if needed (not required for stdio based communication)

CMD ["node", "server.js"]
